"""Added required tables

Revision ID: 5495cf01c7c6
Revises: 0f2546743dd7
Create Date: 2024-09-05 23:36:20.550842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5495cf01c7c6'
down_revision: Union[str, None] = '0f2546743dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('service', sa.String(), nullable=False))
    op.add_column('history', sa.Column('stage', sa.String(), nullable=False))
    op.drop_column('history', 'Stage')
    op.drop_column('history', 'Service')
    op.add_column('patches', sa.Column('service', sa.String(), nullable=False))
    op.add_column('patches', sa.Column('stage', sa.String(), nullable=False))
    op.drop_column('patches', 'Service')
    op.drop_column('patches', 'Stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('Stage', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patches', sa.Column('Service', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('patches', 'stage')
    op.drop_column('patches', 'service')
    op.add_column('history', sa.Column('Service', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('history', sa.Column('Stage', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('history', 'stage')
    op.drop_column('history', 'service')
    # ### end Alembic commands ###
