"""Added required tables

Revision ID: fac6f43a793c
Revises: 
Create Date: 2024-08-29 00:56:17.820792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac6f43a793c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch', sa.JSON(), nullable=False),
    sa.Column('operation', sa.Enum('create', 'update', 'delete', name='openum'), nullable=False),
    sa.Column('timestamp_change', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch', sa.JSON(), nullable=False),
    sa.Column('timestamp_change', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patches')
    op.drop_table('history')
    # ### end Alembic commands ###
