# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example2.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor, descriptor_pool as _descriptor_pool, \
    symbol_database as _symbol_database, runtime_version as _runtime_version
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'example2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xample2.proto\x12\x08\x65xample2\"\x93\x01\n\rServiceConfig\x12\x12\n\x04port\x18\x01 \x01(\x05:\x04\x38\x30\x38\x30\x12\x18\n\x0emonitoring_url\x18\x02 \x01(\t:\x00\x12\x30\n\x07service\x18\x03 \x01(\x0b\x32\x1f.example2.ServiceConfig.Service\x1a\"\n\x07Service\x12\x17\n\ntimeout_ms\x18\x01 \x01(\x05:\x03\x31\x30\x30')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICECONFIG']._serialized_start=29
  _globals['_SERVICECONFIG']._serialized_end=176
  _globals['_SERVICECONFIG_SERVICE']._serialized_start=142
  _globals['_SERVICECONFIG_SERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
