# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\xd0\x01\n\rServiceConfig\x12\x11\n\x04port\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1b\n\x0emonitoring_url\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x34\n\x07service\x18\x03 \x01(\x0b\x32\x1e.example.ServiceConfig.ServiceH\x02\x88\x01\x01\x1a\x31\n\x07Service\x12\x17\n\ntimeout_ms\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\r\n\x0b_timeout_msB\x07\n\x05_portB\x11\n\x0f_monitoring_urlB\n\n\x08_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SERVICECONFIG']._serialized_start=27
  _globals['_SERVICECONFIG']._serialized_end=235
  _globals['_SERVICECONFIG_SERVICE']._serialized_start=146
  _globals['_SERVICECONFIG_SERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
